# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

executors:
  my-executor:
    docker:
      - image: circleci/node:13.8.0

jobs:
  print_hello:
    executor: my-executor
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello"
  print_world:
    executor: my-executor
    steps:
      - run:
          name: "Say Æ¯orld"
          command: "echo World!"
    requires:
      - print_hello

workflows:
  # Name the workflow "welcome"
  sayhello:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world
